# Macro file for NeutronColl
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
/gps/particle gamma
/gps/energy 6 MeV
#
/run/beamOn 5
# 
# proton 210 MeV to the direction (0.,0.,1.)
#
/gps/particle proton
/gps/energy 210 MeV
/tracking/verbose 2
#
/run/beamOn 1
