# Macro file for NeutronColl
# 
# To be run preferably in batch, without graphics:
# % NeutronColl run2.mac
#
#/run/numberOfThreads 4
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#
# gamma 6 MeV to the direction (0.,0.,1.)
# 10000 events
#
/gps/particle neutron
/gps/energy 14 MeV
#
# Make the source produce isotropically
# and at the given x y z position
/gps/ang/type iso
/gps/position 0 0 1 cm
#
/run/printProgress 1000
#
# Define energy as guassian around ~14 MeV
#/gps/ene/type Gauss
/gps/ene/type Lin
/gps/ene/min 13.33 MeV
/gps/ene/max 14.8 MeV
#
# Angular distribution based on P385 data
/gps/ang/type User
/gps/hist/type biast # theta distribution
/control/execute fluxdata_p385.dat
#
/run/beamOn 10000