# Macro file for NeutronColl
# 
# To be run preferably in batch, without graphics:
# % NeutronColl run2.mac
#
#/run/numberOfThreads 4
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#
# gamma 6 MeV to the direction (0.,0.,1.)
# 10000 events
#
/gps/particle neutron
/gps/energy 14 MeV
#
# Make the source produce isotropically
# and at the given x y z position
/gps/ang/type iso
/gps/position 0 0 1 cm
#
/run/printProgress 1000
/run/beamOn 10000
# 